FROM postgres:16.0

COPY scripts /scripts/

ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password

EXPOSE 5432

# FROM python:3.8

# WORKDIR /app

# COPY . .

# RUN pip install -r requirements.txt

# ENV PORT 8080

# EXPOSE 8080

# CMD ["python", "app.py"]